linters:
  # Enable all available linters.
  # Default: false
  enable-all: true
  #disable:
  #  - gofumpt

issues:
  exclude:
    - "Expected*"
  exclude-rules:
    # exclude expectation of \t in imports
    - linters:
        - gci
      text: "Expected.*"
    # exclude File is not gofumpt-ed, while he is
    - linters:
        - gofumpt
      text: "File is not"
    # exclude function too long
    - linters:
        - funlen
      text: ".*is too long.*"
    # exclude function has too many statements
    - linters:
        - funlen
      text: ".*has too many statements.*"

linters-settings:
  errcheck:
    # report about not checking of errors in types assetions: `a := b.(MyStruct)`;
    # default is false: such cases aren't reported by default.
    check-type-assertions: false

    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: false
  govet:
    # report about shadowed variables
    check-shadowing: true
    fieldalignment: true
  golint:
    # minimal confidence for issues, default is 0.8
    min-confidence: 0.8
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true
  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: aprokhorov-praktikum
  goconst:
    # minimal length of string constant, 3 by default
    min-len: 2
    # minimal occurrences count to trigger, 3 by default
    min-occurrences: 2
  fieldalignment:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code
 