SERVER           : 127.0.0.1
PORT             : 8080
POOL_INTERVAL    : 2s
REPORT_INTERVAL  : 10s
MEMSTAT_METRICS  :
  - "Alloc"
  - "BuckHashSys"
  - "Frees"
  - "GCCPUFraction"
  - "GCSys"
  - "HeapAlloc"
  - "HeapIdle"
  - "HeapInuse"
  - "HeapObjects"
  - "HeapReleased"
  - "HeapSys"
  - "LastGC"
  - "Lookups"
  - "MCacheInuse"
  - "MCacheSys"
  - "MSpanInuse"
  - "MSpanSys"
  - "Mallocs"
  - "NextGC"
  - "NumForcedGC"
  - "NumGC"
  - "OtherSys"
  - "PauseTotalNs"
  - "StackInuse"
  - "StackSys"
  - "Sys"
  - "TotalAlloc"
